# site settings
title: Athiben Ananth | Engineering Hub
subtitle: Undergraduate Student @ VIT
email: athiben.ananth@gmail.com
description: Formula 1 Engineering, FEA, Automotive Innovation, Robotics, and the desire to optimize.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://AthibenAnanth.github.io" # the base hostname & protocol for your site
author:
street_address: VIT
city: Vellore
state: TN
zip_code: 632014
country: India
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/AthibenAnanth
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: www.linkedin.com/in/athiben-ananth-mstrcdr110322
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
