backend:
  name: github
  repo: AthibenAnanth/AthibenAnanth.github.io
  branch: master

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Engineering Projects"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
